### PR TITLE
Add support for mustRunAfter and shouldRunAfter as well as more options

### PR DESCRIPTION
**Pull request by leonard84**
New options:
 - color  : allows to specify which color should be used
 - rankdir: controlls the ordering of the graph
 - splines: controlls the edge-shape of the graph
 - includeMustRunAfter  : Include mustRunAfter dependencies in graph
 - includeShouldRunAfter: Include shouldRunAfter dependencies in graph

### CODE REVIEW

**Comment by mmalohlava** [comment]
Thank you @leonard84 ! i will try to review and merge it asap. However, quick question would you be interested in participating in maintenance of this plugin?

**Comment by leonard84** [comment]
@mmalohlava thanks for the quick reply. I can not promise anything, I'm already involved in spock and often don't have enough free time to do everything I want there. These changes are the result of some features I needed for work, so its easy to share them with the community.

**Comment by mmalohlava** [comment]
👍 understand  - thank you for changes! I will try to integrate them asap.

**Comment by leonard84** [comment]
hi @mmalohlava what is the status?

**Comment by leonard84** [comment]
Thanks for merging it, could you publish a new release?

**Comment by mmalohlava** [comment]
@leonard84 1.0.2 is here: https://bintray.com/mmalohlava/gradle-plugins/visteg/1.0.2

**Comment by leonard84** [comment]
thanks

**Pull request merged**
