### PR TITLE
Upgrade to Gradle 5.2.1

### PR DESCRIPTION
**Pull request by hugares**
Adjust to new names and locations of TaskExecutionPlan and TaskInfo
which are ExecutionPlan and TaskNode in Gradle 5.2.1.

https://github.com/mmalohlava/gradle-visteg/issues/12

### CODE REVIEW

**Review by mmalohlava — APPROVED** [review]

**Comment by mmalohlava** [comment]
@hugares Thank you for contribution!

**Comment by hugares** [comment]
Thanks for getting my change in.

Would it be possible to do a release?

**Comment by evantill** [comment]
is there a release ?

**Comment by hugares** [comment]
not yet.
@mmalohlava can you do a release please

**Pull request merged**
