### PR TITLE
Fix compatibility with gradle 4.2, Remove obsolete import of unused code

### PR DESCRIPTION
**Pull request by leonard84**
Add dryRun option to prevent execution of tasks
Fix only apply bintray if bintrayUser is defined

@mmalohlava it would be great if you could merge this and release a new version soon

### CODE REVIEW

**Comment by leonard84** [comment]
@mmalohlava sorry to nag, but I need this to finish my ticket

**Review by mmalohlava — APPROVED** [review]

**Comment by mmalohlava** [comment]
Thank you! @leonard84 !

**Comment by mmalohlava** [comment]
New version uploaded: https://bintray.com/mmalohlava/gradle-plugins/visteg/1.0.3

**Comment by mmalohlava** [comment]
@leonard84 i added you as collaborator to this repo.

**Pull request merged**
